baseURL = "https://icgk523.github.io/MicrobiomeGreenRevolution.github.io/"
languageCode = 'en-us'
title = 'Microbiome Green Revolution'
theme = "ananke"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Team"
    url = "/team/"
    weight = 2

  [[menu.main]]
    name = "Contact Us"
    url = "/contact-us/"
    weight = 3


